name: Destroy Infrastructure

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  destroy:
    name: Destroy Infrastructure for ${{ github.ref_name == 'main' && 'production' || 'development' }}
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DIGITALOCEAN_SPACES_ACCESS_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DIGITALOCEAN_SPACES_SECRET_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        working-directory: infra/terraform
        run: |
          terraform init \
            -backend-config="key=infra/${ENVIRONMENT}/terraform.tfstate"

      - name: Terraform Destroy
        working-directory: infra/terraform
        run: |
          terraform destroy -auto-approve \
            -var="image=ubuntu-25-04-x64" \
            -var="env_name=${ENVIRONMENT}" \
            -var="instance_size=s-1vcpu-512mb-10gb" \
            -var="do_token=${DIGITALOCEAN_TOKEN}" \
            -var="spaces_access_id=${AWS_ACCESS_KEY_ID}" \
            -var="spaces_secret_key=${AWS_SECRET_ACCESS_KEY}"
