name: Destroy Infrastructure

on:
  workflow_dispatch: # <-- executa manualmente pelo botÃ£o "Run workflow"

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      DIGITALOCEAN_ENVIRONMENT: dev
      AWS_ACCESS_KEY_ID: ${{ secrets.DIGITALOCEAN_SPACES_ACCESS_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DIGITALOCEAN_SPACES_SECRET_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        working-directory: infra/terraform
        run: |
          terraform init \
            -backend-config="key=infra/${DIGITALOCEAN_ENVIRONMENT}/terraform.tfstate"

      - name: Terraform Destroy
        working-directory: infra/terraform
        run: |
          terraform destroy -auto-approve \
            -var="image=ubuntu-25-04-x64" \
            -var="env_name=${DIGITALOCEAN_ENVIRONMENT}" \
            -var="instance_size=s-1vcpu-512mb-10gb" \
            -var="public_key=${SSH_PUBLIC_KEY}" \
            -var="do_token=${DIGITALOCEAN_TOKEN}" \
            -var="spaces_access_id=${AWS_ACCESS_KEY_ID}" \
            -var="spaces_secret_key=${AWS_SECRET_ACCESS_KEY}"
